# Generated by Django 5.1.5 on 2025-01-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
